name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  checks: write
  contents: read
  pull-requests: read
jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: ConorMacBride/install-package@v1
        with:
          apt: just
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: test
        run: just test
